[pytest]
testpaths = tests
pythonpath = src
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore:Using `httpx` with `starlette.testclient`:Warning
